/**
 * @description       : 
 * @author            : michele11.argentino@nttdata.com
 * @group             : 
 * @last modified on  : 03-05-2026
 * @last modified by  : michele11.argentino@nttdata.com
**/

@isTest
private class KHC_CaseClassTest { 

    @isTest
    static void myUnitTest() {
        KHC_CaseClass test = new KHC_CaseClass();
        KHC_CaseClass.test1();
        KHC_CaseClass.test2();
        KHC_CaseClass.test3();
        //test
    }
}

